language: java


matrix:
  include:
    ## http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
    - os: linux
      sudo: required
      dist: trusty
      jdk: oraclejdk8
      install: true
      env: FAILURES_ALLOWED=false
    - os: linux
      sudo: false
      jdk: oraclejdk8
      env: FAILURES_ALLOWED=true
      # older than 1.8.0_40 will fail compiling since javafx-maven-plugin 8.8.0
    - os: osx
      osx_image: xcode8
      env: FAILURES_ALLOWED=false
  allow_failures:
    - env: FAILURES_ALLOWED=true

## maven-invoker-plugin is called after deploying javafx-maven-plugin into local repository, so change default-test-call to "install" (because its called at that maven-phase)
script:
  - mvnw install -B

branches:
  only:
  - master

notifications:
  email: false
